version: '3.1'

services:
    memcached:
        image: 'memcached:alpine'

    redis:
        image: 'redis:alpine'

    mysql:
        image: 'mysql:8.0'
        working_dir: /www
        volumes:
            - '.:/www'
        environment:
            - MYSQL_ROOT_PASSWORD=root_password_here
            - MYSQL_DATABASE=app
            - MYSQL_USER=user
            - MYSQL_PASSWORD=user_password_here
        ports:
            - '63002:3306'

    webserver:
        image: 'nginx:alpine'
        working_dir: /www
        volumes:
            - '.:/www'
            - './conf/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '63000:80'

    php-fpm:
        build: conf/php-fpm
        working_dir: /www
        volumes:
            - '.:/www'
            - './conf/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
